apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-rammemeldinger
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  accessPolicy:
    outbound:
      rules:
        - application: omsorgspenger-tilgangsstyring
      external:
      {{#each externalHosts as |host|}}
        - host: {{host}}
      {{/each}}
    inbound:
      rules:
        - application: omsorgspenger-oidc-auth-proxy
        - application: k9-aarskvantum
          namespace: default
          cluster: {{clusterFss}}
  strategy:
    type: RollingUpdate
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        diskAutoresize: true
        tier: {{ database.tier }}
        diskSize: {{ database.diskSize }}
        highAvailability: {{ database.highAvailability }}
        databases:
          - name: omsorgspenger-rammemeldinger
            envVarPrefix: DATABASE
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  preStopHookPath: "/internal/pre-stop"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  filesFrom:
    - secret: omsorgspenger-meldinger-srvusercredentials
      mountPath: /var/run/secrets/nais.io/service_user
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: TILGANGSSTYRING_URL
      value: http://omsorgspenger-tilgangsstyring.omsorgspenger.svc.cluster.local