apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-rammemeldinger
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    outbound:
      rules:
        - application: omsorgspenger-tilgangsstyring
        - application: omsorgspenger-infotrygd-rammevedtak
    inbound:
      rules:
        - application: omsorgsdager
        - application: k9-aarskvantum
          namespace: k9saksbehandling
          cluster: {{clusterFss}}
  strategy:
    type: RollingUpdate
  gcp:
    sqlInstances:
      - type: {{ database.type }}
        diskAutoresize: true
        tier: {{ database.tier }}
        diskSize: {{ database.diskSize }}
        highAvailability: {{ database.highAvailability }}
        {{#if database.enableAudit }}
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "all"
          - name: "pgaudit.log_parameter"
            value: "on"
        {{/if}}
        databases:
          - name: omsorgspenger-rammemeldinger
            envVarPrefix: DATABASE

  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: TILGANGSSTYRING_URL
      value: http://omsorgspenger-tilgangsstyring.omsorgspenger.svc.cluster.local
    - name: OMSORGSPENGER_INFOTRYGD_RAMMEVEDTAK_BASE_URL
      value: http://omsorgspenger-infotrygd-rammevedtak.omsorgspenger.svc.cluster.local
    - name: KAFKA_RAPID_TOPIC
      value: omsorgspenger.k9-rapid-v2
    - name: KAFKA_CONSUMER_GROUP_ID
      value: omsorgspenger-rammemelding
