name: Build Pull Request
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'

jobs:
  test:
    uses: navikt/sif-gha-workflows/.github/workflows/gradle-test.yml@copilot/add-scan-for-sensitive-data-action
    permissions:
      contents: read
    secrets: inherit
    with:
      javaversion: 21
